# -*- coding: utf-8 -*-
"""Indian Startups.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZcEKumJdoahP4O-GOpP2EzBwAuKv-ZQ
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
# %matplotlib inline

from plotly import tools
import plotly.offline as py

import plotly.graph_objs as go
# import plotly.express as px

# pd.options.mode.chained_assignment = None
# pd.options.display.max_columns = 999

df=pd.read_csv('/content/Indian startuo data Kaggle-Modified 1.csv')
df.columns = ["SNo", "Date", "StartupName", "IndustryVertical", "SubVertical", "City", "InvestorsName", "InvestmentType", "AmountInUSD"]

df.head()

df.shape

df.drop(['SNo'],axis='columns',inplace=True)

def clean_string(x):
     return str(x).replace("\\xc2\\xa0","").replace("\\\\xc2\\\\xa0", "")

for col in ["StartupName", "IndustryVertical", "SubVertical", "City", "InvestorsName", "InvestmentType", "AmountInUSD"]:
   df[col] = df[col].apply(lambda x: clean_string(x))

df.head()

df.shape

df.describe()

df.info()

df.isnull().sum()

percent_null=df.isnull().sum()/len(df)
percent_null

#Replacing NAN values
df['SubVertical']=df['SubVertical'].fillna(df['SubVertical'].mode()[0])
df['City']=df['City'].fillna(df['City'].mode()[0])
df['IndustryVertical']=df['IndustryVertical'].fillna(df['IndustryVertical'].mode()[0])
df['InvestorsName']=df['InvestorsName'].fillna(df['InvestorsName'].mode()[0])
df['InvestmentType']=df['InvestmentType'].fillna(df['InvestmentType'].mode()[0])
#df['AmountInUSD'].fillna(df['AmountInUSD'].median(),inplace=True)
#df['AmountInUSD'].fillna(df['AmountInUSD'].median(),inplace=True)
df.head()

df.isnull().sum()

percent_null=df.isnull().sum()/len(df)
percent_null

import regex

df["AmountInUSD"]=df["AmountInUSD"].replace(",","")
df["AmountInUSD"]=df["AmountInUSD"].replace("[A-za-z/d+],","")
#df["AmountInUSD"]=df["AmountInUSD"].str.replace("unknown","")
df["AmountInUSD"]=pd.to_numeric(df["AmountInUSD"])

df['City'].value_counts()
City=df['City'].value_counts()
City=pd.DataFrame({'City':City.index,'Count':City.values})
City

Most_Startups=City.nlargest(20,'Count')
Most_Startups

fig = px.pie(Most_Startups, values='Count', names='City', title='Most Startups',width=1000, height=800)

fig.show(renderer="colab")

fig = px.bar(City, x='City', y='Count',width=1000, height=800,text_auto=True)

fig.show(renderer="colab")

pd.set_option('display.float_format', '{:.2f}'.format)
Most_Funded_City=df.groupby('City').agg({'AmountInUSD':sum}).reset_index().nlargest(20,'AmountInUSD')
Most_Funded_City

fig = px.bar(Most_Funded_City, x='City', y='AmountInUSD',width=1000, height=800,text_auto=True)

fig.show(renderer="colab")

"""Startups_Sectorwise"""

Sectors=df['IndustryVertical'].value_counts()
Sectors

Sectors_Startups=pd.DataFrame({'Sectors':Sectors.index,'Count':Sectors.values})
Sectors_Startups

Largest_Sectors=Sectors_Startups.nlargest(20,'Count')
Largest_Sectors

pd.set_option('display.float_format', '{:.2f}'.format)
Most_Funded_Sectors=df.groupby('IndustryVertical').agg({'AmountInUSD':sum}).reset_index().nlargest(20,'AmountInUSD')
Most_Funded_Sectors

fig = px.pie(Most_Funded_Sectors, values='AmountInUSD', names='IndustryVertical', title='Most_Funded_Sectors',width=1000, height=800)

fig.show(renderer="colab")

fig = px.bar(Most_Funded_Sectors, x='IndustryVertical', y='AmountInUSD',width=1000, height=800,text_auto=True)

fig.show(renderer="colab")

Sub_Vertical=df['SubVertical'].value_counts()
Sub_Vertical

Sub_Vertical_Startups=pd.DataFrame({'Sectors':Sub_Vertical.index,'Count':Sub_Vertical.values})
Sub_Vertical_Startups

LargestSub_Verticals=Sectors_Startups.nlargest(20,'Count')
LargestSub_Verticals

pd.set_option('display.float_format', '{:.2f}'.format)
Most_Funded_SubVertical=df.groupby('SubVertical').agg({'AmountInUSD':sum}).reset_index().nlargest(20,'AmountInUSD')
Most_Funded_SubVertical

Amounts_Invested=df['AmountInUSD'].value_counts()
Amounts_Invested

fig = px.pie(Most_Funded_SubVertical, values='AmountInUSD', names='SubVertical', title='Most Funded SubVerticals',width=1000, height=800)

fig.show(renderer="colab")

fig = px.bar(Most_Funded_SubVertical, x='SubVertical', y='AmountInUSD',width=1000, height=800,text_auto=True)

fig.show(renderer="colab")

"""Number Of Fundings
In this section, let us see how the number of fundings have changed over time
"""

df['InvestorsName'].value_counts()

Big_Investors=df.groupby('InvestorsName').agg({'AmountInUSD':sum}).nlargest(20,'AmountInUSD').reset_index()
Big_Investors

fig = px.bar(Big_Investors, x='InvestorsName', y='AmountInUSD',width=1000, height=800,text_auto=True)

fig.show(renderer="colab")

fig = px.pie(Big_Investors, values='AmountInUSD', names='InvestorsName', title='Big Inestors',width=1000, height=800)

fig.show(renderer="colab")

City_wise=df.groupby(['City','StartupName','InvestorsName']).agg({'AmountInUSD':sum}).nlargest(30,'AmountInUSD').reset_index()
City_wise

fig = px.bar(City_wise, x='StartupName', y='AmountInUSD',color='InvestorsName',title='StartupName,InvestorsName',text_auto=True,width=2000, height=800,)

fig.show(renderer="colab")

Investment_type=df.groupby('InvestmentType').agg({'AmountInUSD':sum}).nlargest(20,'AmountInUSD').reset_index()
Investment_type

fig = px.pie(Investment_type, values='AmountInUSD', names='InvestmentType', title='Most Funded SubVerticals',width=1000, height=800)

fig.show(renderer="colab")

